/* Plant Care Companion — dati botanici e di cura.
   Autore: Edoardo Giangrandi — © 2026, licenza MIT */

export const BOTANICA = {
  "Monstera deliciosa": { f: "Araceae", o: "Messico meridionale e Panama",
    h: "Emiemifita: germina a terra, trova un tronco e ci sale sopra usando radici aeree, perdendo poi il contatto col suolo.",
    c: "I buchi non sono un vezzo: lasciano passare il vento e la luce alle foglie sottostanti nel sottobosco. Compaiono solo con la maturità, e il frutto maturo è l'unica parte commestibile della pianta.",
    t: "Tossica: tutta la pianta contiene ossalati di calcio, che bruciano bocca e gola." },
  "Monstera adansonii": { f: "Araceae", o: "America centrale e meridionale",
    h: "Rampicante di sottobosco, sale sui tronchi in ombra parziale.",
    c: "Le fenestrazioni ci sono fin da giovane, al contrario della deliciosa. In natura arriva a coprire interi tronchi.",
    t: "Tossica: ossalati di calcio." },
  "Monstera adansonii Mint (variegata)": { f: "Araceae", o: "Selezione orticola",
    h: "Come la specie, ma le parti bianche non fanno fotosintesi.",
    c: "La variegatura è una mutazione instabile: la pianta può tornare tutta verde, e in quel caso cresce molto più in fretta perché smette di sprecare energia.",
    t: "Tossica: ossalati di calcio." },
  "Alocasia": { f: "Araceae", o: "Sud-est asiatico e Australia orientale",
    h: "Sottobosco umido tropicale, da rizoma o tubero.",
    c: "In inverno può perdere tutte le foglie ed entrare in dormienza: sembra morta ma il tubero è vivo, e ributta a marzo. È il motivo per cui ne finiscono migliaia nel bidone ogni anno.",
    t: "Tossica: ossalati di calcio, tra le più irritanti del gruppo." },
  "Alocasia amazonica (Polly)": { f: "Araceae", o: "Nessuna: è un ibrido di vivaio",
    h: "Incrocio orticolo, in natura non esiste.",
    c: "Il nome inganna: non ha niente a che fare con l'Amazzonia. Deriva dal vivaio Amazon Nursery della Florida, dove l'ibrido fu creato negli anni Cinquanta.",
    t: "Tossica: ossalati di calcio." },
  "Anthurium regale": { f: "Araceae", o: "Perù",
    h: "Epifita: cresce aggrappata ai tronchi, con le radici all'aria.",
    c: "Le foglie velluto arrivano a un metro in natura. Quell'effetto vellutato viene da cellule epidermiche a cupola che catturano la poca luce del sottobosco, ed è anche il motivo per cui una goccia d'acqua lascia il segno per sempre.",
    t: "Tossica: ossalati di calcio." },
  "Anthurium warocqueanum": { f: "Araceae", o: "Colombia",
    h: "Epifita di foresta nebulosa, tra i 200 e i 1500 metri.",
    c: "La chiamano queen anthurium: le foglie pendenti superano il metro e mezzo. Cresce lentissima e vuole umidità che in casa non esiste, ed è per questo che è una delle piante più difficili in commercio.",
    t: "Tossica: ossalati di calcio." },
  "Howea forsteriana (kentia)": { f: "Arecaceae", o: "Madagascar, endemica",
    h: "Cresce lungo i corsi d'acqua, con le radici quasi sempre umide.",
    c: "In natura arriva a dodici metri, e in Madagascar è minacciata: ne restano poche popolazioni selvatiche. Quella che compri nei supermercati è tutta da coltivazione.",
    t: "Non tossica." },
  "Epipremnum aureum (pothos)": { f: "Araceae", o: "Moorea, Polinesia francese",
    h: "Rampicante che in natura sale sugli alberi fino a venti metri.",
    c: "Le foglie che conosci sono giovanili: se lasciata salire su un tronco produce foglie da un metro, fenestrate come una monstera. È anche una specie invasiva grave in molte zone tropicali.",
    t: "Tossica: ossalati di calcio." },
  "Spathiphyllum (spatifillo)": { f: "Araceae", o: "America centrale e Colombia",
    h: "Sottobosco umido di foresta pluviale.",
    c: "Il fiore non è il fiore: la parte bianca è una brattea, e i fiori veri sono i puntini sulla pannocchia centrale. Fiorisce solo con abbastanza luce, quindi in penombra resta verde per anni.",
    t: "Tossica: ossalati di calcio." },
  "Maranta leuconeura": { f: "Marantaceae", o: "Foresta pluviale brasiliana",
    h: "Tappezzante di sottobosco, in ombra profonda.",
    c: "Di notte alza le foglie e le chiude come mani giunte: si chiama nictinastia ed è un movimento vero, guidato da cuscinetti d'acqua alla base del picciolo. Da lì il nome di pianta della preghiera.",
    t: "Non tossica." },
  "Calathea": { f: "Marantaceae", o: "America tropicale",
    h: "Sottobosco umido, all'ombra di alberi alti.",
    c: "Nel 2012 gran parte delle calathee è stata riclassificata nel genere Goeppertia: quello che compri come Calathea spesso ha già un altro nome scientifico.",
    t: "Non tossica." },
  "Fittonia albivenis": { f: "Acanthaceae", o: "Perù e bacino amazzonico",
    h: "Tappeto del sottobosco, in ombra e umidità costante.",
    c: "Il reticolo bianco sono le nervature: albivenis vuol dire proprio vene bianche. Il crollo teatrale quando ha sete è un meccanismo di risparmio idrico, non un danno.",
    t: "Non tossica." },
  "Chlorophytum (spider plant)": { f: "Asparagaceae", o: "Africa australe",
    h: "Sottobosco e zone rocciose, con radici tuberose che immagazzinano acqua.",
    c: "Fa figli su stoloni lunghi anche un metro: è una delle poche piante d'appartamento che si clona da sola. Ed è tra le pochissime del tutto sicure per i gatti.",
    t: "Non tossica." },
  "Sansevieria (snake plant)": { f: "Asparagaceae", o: "Africa occidentale tropicale",
    h: "Zone aride e rocciose, in pieno sole o mezz'ombra.",
    c: "Dal 2017 il genere Sansevieria è stato assorbito in Dracaena. Fa fotosintesi CAM: apre gli stomi di notte per perdere meno acqua, come i cactus.",
    t: "Lievemente tossica se ingerita." },
  "Sansevieria intrecciata": { f: "Asparagaceae", o: "Africa occidentale tropicale",
    h: "Come la specie: l'intreccio è lavorazione da vivaio.",
    c: "Le foglie sono state legate da giovani e sono cresciute così. Nel punto d'incrocio l'acqua ristagna, ed è lì che comincia il marciume.",
    t: "Lievemente tossica se ingerita." },
  "Peperomia polybotrya (raindrop)": { f: "Piperaceae", o: "Perù e Colombia",
    h: "Epifita e rupicola, spesso su rocce coperte di muschio.",
    c: "Parente stretta del pepe nero. Le foglie carnose sono una riserva d'acqua: per questo tollera di essere dimenticata e non tollera il terriccio zuppo.",
    t: "Non tossica." },
  "Peperomia obtusifolia": { f: "Piperaceae", o: "Florida, Caraibi e Sud America",
    h: "Epifita nelle foreste umide, su tronchi e ceppaie.",
    c: "Si moltiplica da una sola foglia con un pezzo di picciolo: una delle propagazioni più facili che esistano.",
    t: "Non tossica." },
  "Phlebodium aureum (felce blu)": { f: "Polypodiaceae", o: "America tropicale e subtropicale",
    h: "Epifita: vive sui tronchi e alla base delle palme, mai nella terra.",
    c: "Il rizoma è coperto di squame dorate, da cui aureum. La sfumatura azzurra viene da una cera superficiale che riflette la luce: se strofini le foglie va via e non torna.",
    t: "Non tossica." },
  "Felce rustica da esterno": { f: "Dryopteridaceae", o: "Boschi temperati dell'emisfero nord",
    h: "Sottobosco fresco e ombroso, su terreni ricchi di foglie decomposte.",
    c: "Le felci non hanno né fiori né semi: si riproducono con spore, e sulla pagina inferiore delle fronde vedrai i sori, i puntini scuri che le contengono.",
    t: "Non tossica per contatto." },
  "Hedera helix (edera)": { f: "Araliaceae", o: "Europa e Asia occidentale",
    h: "Rampicante di bosco, si arrampica con radichette avventizie.",
    c: "Ha due forme distinte: da giovane rampicante con foglie a lobi, da adulta arbustiva con foglie intere, e solo in quella forma fiorisce. Le talee mantengono la forma da cui provengono.",
    t: "Tossica: bacche e foglie contengono saponine." },
  "Pilea peperomioides": { f: "Urticaceae", o: "Yunnan, Cina sud-occidentale",
    h: "Rupicola: cresce su rocce ombrose ai piedi dell'Himalaya.",
    c: "Per decenni è stata quasi sconosciuta ai botanici occidentali: si è diffusa in Europa dagli anni Quaranta passando di mano in mano come talea, portata da un missionario norvegese, prima ancora di essere identificata con certezza.",
    t: "Non tossica." },
  "Hypoestes (polka dot)": { f: "Acanthaceae", o: "Madagascar",
    h: "Sottobosco umido.",
    c: "Le macchie rosa sono aree prive di clorofilla: più luce riceve, più il disegno è marcato. In ombra sbiadisce e la pianta si allunga.",
    t: "Non tossica." },
  "Sedum nussbaumerianum": { f: "Crassulaceae", o: "Veracruz, Messico",
    h: "Scarpate rocciose assolate, con pochissimo suolo.",
    c: "Le foglie virano al rame per proteggersi dall'eccesso di luce: è un pigmento protettivo, quindi il colore che ti piace è letteralmente una scottatura controllata. La patina bianca sopra è cera, e una volta tolta con le dita non ricresce su quella foglia.",
    t: "Non tossica." },
  "Philodendron": { f: "Araceae", o: "America tropicale",
    h: "Rampicanti ed emiemifite di foresta pluviale.",
    c: "È il secondo genere più numeroso delle Araceae: quasi cinquecento specie descritte, e molte ancora no.",
    t: "Tossica: ossalati di calcio." },
};

export const EN_BOTANICA = {
  "Monstera deliciosa": { f: "Araceae", o: "Southern Mexico and Panama",
    h: "Hemiepiphyte: it germinates on the ground, finds a trunk and climbs it with aerial roots, eventually losing contact with the soil.",
    c: "The holes aren't decoration: they let wind and light through to the leaves below in the understorey. They only appear with maturity, and the ripe fruit is the one edible part of the plant.",
    t: "Toxic: the whole plant contains calcium oxalate, which burns mouth and throat." },
  "Monstera adansonii": { f: "Araceae", o: "Central and South America",
    h: "Understorey climber, going up trunks in partial shade.",
    c: "The fenestrations are there from a young age, unlike deliciosa. In the wild it covers entire trunks.",
    t: "Toxic: calcium oxalate." },
  "Monstera adansonii Mint (variegata)": { f: "Araceae", o: "Horticultural selection",
    h: "Like the species, but with pale green leaf sectors rather than white ones.",
    c: "Mint differs from white variegation: the pale sectors still contain chlorophyll, so they work. It grows faster, burns far less in sun, and the variegation is much more stable — it rarely reverts.",
    t: "Toxic: calcium oxalate." },
  "Alocasia": { f: "Araceae", o: "South-east Asia and eastern Australia",
    h: "Humid tropical understorey, from a rhizome or tuber.",
    c: "In winter it can drop every leaf and go dormant: it looks dead but the tuber is alive and shoots again in March. Thousands end up in the bin every year for this reason.",
    t: "Toxic: calcium oxalate, among the most irritating of the group." },
  "Alocasia amazonica (Polly)": { f: "Araceae", o: "None: it's a nursery hybrid",
    h: "A horticultural cross; it doesn't exist in the wild.",
    c: "The name misleads: nothing to do with the Amazon. It comes from the Amazon Nursery in Florida, where the hybrid was created in the 1950s.",
    t: "Toxic: calcium oxalate." },
  "Anthurium regale": { f: "Araceae", o: "Peru",
    h: "Epiphyte: it grows clinging to trunks, roots in the air.",
    c: "Velvet leaves reach a metre in the wild. That velvet comes from dome-shaped epidermal cells that capture the scarce understorey light — and it's also why a single water droplet leaves a permanent mark.",
    t: "Toxic: calcium oxalate." },
  "Anthurium warocqueanum": { f: "Araceae", o: "Colombia",
    h: "Cloud-forest epiphyte, between 200 and 1500 metres.",
    c: "They call it the queen anthurium: the hanging leaves pass a metre and a half. It grows very slowly and wants humidity that doesn't exist indoors, which is why it's one of the hardest plants in the trade.",
    t: "Toxic: calcium oxalate." },
  "Howea forsteriana (kentia)": { f: "Arecaceae", o: "Lord Howe Island, Australia — endemic",
    h: "Subtropical forest understorey: it grows in the shade of taller trees, not in full sun.",
    c: "All of them come from an eleven-square-kilometre island in the Pacific, where seed collection and export are regulated by law and are the main local industry. It's the Victorian parlour palm precisely because it takes low light and dry air better than any other.",
    t: "Not toxic." },
  "Epipremnum aureum (pothos)": { f: "Araceae", o: "Moorea, French Polynesia",
    h: "A climber that goes twenty metres up trees in the wild.",
    c: "The leaves you know are juvenile: let it climb a trunk and it makes metre-long fenestrated leaves like a monstera. It's also a serious invasive species across the tropics.",
    t: "Toxic: calcium oxalate." },
  "Spathiphyllum (spatifillo)": { f: "Araceae", o: "Central America and Colombia",
    h: "Humid rainforest understorey.",
    c: "The flower isn't the flower: the white part is a bract, and the real flowers are the dots on the central spike. It only blooms with enough light, so in shade it stays green for years.",
    t: "Toxic: calcium oxalate." },
  "Maranta leuconeura": { f: "Marantaceae", o: "Brazilian rainforest",
    h: "Understorey ground cover, in deep shade.",
    c: "At night it raises its leaves and folds them like praying hands: it's called nyctinasty, a real movement driven by water cushions at the base of each stalk. Hence the name prayer plant.",
    t: "Not toxic." },
  "Calathea": { f: "Marantaceae", o: "Tropical America",
    h: "Humid understorey, shaded by taller trees.",
    c: "In 2012 most calatheas were reclassified into the genus Goeppertia: what you buy as Calathea often already has another scientific name.",
    t: "Not toxic." },
  "Fittonia albivenis": { f: "Acanthaceae", o: "Peru and the Amazon basin",
    h: "Forest-floor carpet, in shade and constant humidity.",
    c: "The white net is the veins: albivenis literally means white-veined. The theatrical collapse when thirsty is a water-saving mechanism, not damage.",
    t: "Not toxic." },
  "Chlorophytum (spider plant)": { f: "Asparagaceae", o: "Southern Africa",
    h: "Understorey and rocky ground, with tuberous roots that store water.",
    c: "It makes babies on runners up to a metre long: one of the few houseplants that clones itself. And one of the very few completely safe around cats.",
    t: "Not toxic." },
  "Sansevieria (snake plant)": { f: "Asparagaceae", o: "Tropical West Africa",
    h: "Arid, rocky ground, in full sun or partial shade.",
    c: "Since 2017 the genus Sansevieria has been absorbed into Dracaena. It runs CAM photosynthesis: stomata open at night to lose less water, like cacti.",
    t: "Mildly toxic if eaten." },
  "Sansevieria intrecciata": { f: "Asparagaceae", o: "Tropical West Africa",
    h: "As the species: the braid is nursery work.",
    c: "The leaves were tied young and grew that way. Water pools where they cross, and that's where rot starts.",
    t: "Mildly toxic if eaten." },
  "Peperomia polybotrya (raindrop)": { f: "Piperaceae", o: "Peru and Colombia",
    h: "Epiphytic and rock-dwelling, often on moss-covered stone.",
    c: "A close relative of black pepper. The fleshy leaves are a water store: that's why it tolerates being forgotten and won't tolerate soggy soil.",
    t: "Not toxic." },
  "Peperomia obtusifolia": { f: "Piperaceae", o: "Florida, the Caribbean and South America",
    h: "Epiphytic in humid forest, on trunks and stumps.",
    c: "It propagates from a single leaf with a piece of stalk: one of the easiest propagations there is.",
    t: "Not toxic." },
  "Phlebodium aureum (felce blu)": { f: "Polypodiaceae", o: "Tropical and subtropical America",
    h: "Epiphyte: it lives on trunks and at the base of palms, never in soil.",
    c: "The rhizome is covered in golden scales, hence aureum. The blue cast comes from a surface wax that reflects light: rub the leaves and it goes, permanently.",
    t: "Not toxic." },
  "Felce rustica da esterno": { f: "Dryopteridaceae", o: "Temperate woodland of the northern hemisphere",
    h: "Cool shaded understorey, on soil rich in leaf litter.",
    c: "Ferns have neither flowers nor seeds: they reproduce by spores, and on the underside of the fronds you'll see the sori, the dark dots that hold them.",
    t: "Not toxic to the touch." },
  "Hedera helix (edera)": { f: "Araliaceae", o: "Europe and western Asia",
    h: "Woodland climber, gripping with adventitious rootlets.",
    c: "It has two distinct forms: juvenile and climbing with lobed leaves, adult and shrubby with entire leaves, and only the adult form flowers. Cuttings keep whichever form they came from.",
    t: "Toxic: berries and leaves contain saponins." },
  "Pilea peperomioides": { f: "Urticaceae", o: "Yunnan, south-west China",
    h: "Rock-dweller: it grows on shaded rock at the foot of the Himalayas.",
    c: "For decades it was nearly unknown to Western botanists: it spread through Europe from the 1940s hand to hand as cuttings, carried by a Norwegian missionary, before it had been firmly identified.",
    t: "Not toxic." },
  "Hypoestes (polka dot)": { f: "Acanthaceae", o: "Madagascar",
    h: "Humid understorey.",
    c: "The pink patches are areas without chlorophyll: the more light it gets, the stronger the pattern. In shade it fades and the plant stretches.",
    t: "Not toxic." },
  "Sedum nussbaumerianum": { f: "Crassulaceae", o: "Veracruz, Mexico",
    h: "Sunny rocky slopes, with almost no soil.",
    c: "The leaves turn copper to protect themselves from excess light: it's a protective pigment, so the colour you like is literally a controlled sunburn. The white bloom on top is wax, and once rubbed off with your fingers it never returns on that leaf.",
    t: "Not toxic." },
  "Philodendron": { f: "Araceae", o: "Tropical America",
    h: "Climbers and hemiepiphytes of the rainforest.",
    c: "The second largest genus in the Araceae: nearly five hundred described species, and many still not.",
    t: "Toxic: calcium oxalate." },
};

export const BOT_PIU = {
  "Monstera deliciosa": { nc: "Filodendro spaccafoglie", nce: "Swiss cheese plant",
    d: "In natura sale 20 m; in casa 2-3 m con foglie di 60 cm", de: "20 m in the wild; 2-3 m indoors with 60 cm leaves",
    tmin: "12 °C", um: "media", err: "Annaffiarla prima che asciughi: le radici carnose marciscono in fretta.", erre: "Watering before it dries: the fleshy roots rot quickly.",
    gu: "Il punto dove il picciolo entra nel fusto: la cocciniglia farinosa comincia sempre da lì.", gue: "Where the stalk meets the stem: mealybugs always start there." },
  "Monstera adansonii": { nc: "Monstera buchi", nce: "Swiss cheese vine",
    d: "Tralci di diversi metri, foglie sui 20-30 cm", de: "Stems several metres long, leaves 20-30 cm",
    tmin: "12 °C", um: "medio-alta", err: "Lasciare il palo asciutto: senza umido le radici aeree non si aggrappano e le foglie restano piccole.", erre: "Leaving the pole dry: without moisture the aerial roots won't grip and the leaves stay small.",
    gu: "Le radici aeree sul palo: se sono secche e non aderiscono, il palo è troppo asciutto.", gue: "The aerial roots on the pole: dry and not gripping means the pole is too dry." },
  "Monstera adansonii Mint (variegata)": { nc: "Monstera mint", nce: "Mint monstera",
    d: "Come la specie, ma cresce più lenta", de: "As the species, but slower",
    tmin: "12 °C", um: "medio-alta", err: "Metterla al sole pieno pensando che serva alla variegatura: i settori chiari si bruciano.", erre: "Putting it in full sun for the variegation: the pale sectors scorch.",
    gu: "I settori chiari: se ingialliscono oltre il bianco crema, è troppa luce.", gue: "The pale sectors: if they go past cream into yellow, it's too much light." },
  "Alocasia": { nc: "Orecchie d'elefante", nce: "Elephant ear",
    d: "Da 40 cm a oltre 1,5 m secondo la specie", de: "From 40 cm to over 1.5 m depending on species",
    tmin: "15 °C", um: "alta", err: "Buttarla quando perde le foglie d'inverno: il tubero è vivo e ributta a marzo.", erre: "Binning it when it drops its leaves in winter: the tuber is alive and returns in March.",
    gu: "Il rovescio delle foglie, contro luce: le ragnatele del ragnetto rosso si vedono solo così.", gue: "The undersides against the light: spider mite webbing shows up only that way." },
  "Alocasia amazonica (Polly)": { nc: "Alocasia Polly", nce: "Alocasia Polly",
    d: "Resta compatta: 40-60 cm", de: "Stays compact: 40-60 cm",
    tmin: "15 °C", um: "alta", err: "Non controllare il rovescio delle foglie: il ragnetto rosso arriva prima che te ne accorga.", erre: "Not checking the leaf undersides: spider mites arrive before you notice.",
    gu: "Il rovescio delle foglie e l'ascella dei piccioli, i due nascondigli preferiti dai parassiti.", gue: "Leaf undersides and the leaf axils, the two favourite hiding places for pests." },
  "Anthurium regale": { nc: "Anturio regale", nce: "Regal anthurium",
    d: "Foglie fino a 1 m in serra, 40-50 cm in casa", de: "Leaves to 1 m in a greenhouse, 40-50 cm indoors",
    tmin: "16 °C", um: "molto alta", err: "Bagnare le foglie: sul velluto ogni goccia lascia un segno che non va più via.", erre: "Wetting the leaves: on velvet every drop leaves a permanent mark.",
    gu: "La foglia nuova mentre è ancora arrotolata: i tripidi la rovinano prima che si apra.", gue: "The new leaf while still furled: thrips ruin it before it opens." },
  "Anthurium warocqueanum": { nc: "Anturio regina", nce: "Queen anthurium",
    d: "Foglie pendenti oltre 1,5 m in natura", de: "Hanging leaves over 1.5 m in the wild",
    tmin: "16 °C", um: "molto alta", err: "Tenerla in casa senza serretta: l'aria di un appartamento è troppo secca per lei.", erre: "Keeping it in a room without a case: household air is far too dry for it.",
    gu: "Lo sfagno attorno al colletto: se resta fradicio, il fusto marcisce da lì.", gue: "The sphagnum around the crown: if it stays soaked, the stem rots from there." },
  "Howea forsteriana (kentia)": { nc: "Palma kentia", nce: "Kentia palm",
    d: "12 m sull'isola, 2-3 m in salotto dopo molti anni", de: "12 m on its island, 2-3 m indoors after many years",
    tmin: "10 °C", um: "media", err: "Tenerla sempre umida: muore molto più spesso di troppa acqua che di poca.", erre: "Keeping it always damp: it dies of too much water far more often than too little.",
    gu: "Le punte delle foglie più basse: seccano per prime quando l'acqua è troppo dura.", gue: "The tips of the lowest fronds: they brown first when the water is too hard." },
  "Epipremnum aureum (pothos)": { nc: "Potos", nce: "Golden pothos",
    d: "Tralci di metri; foglie giovanili 10 cm, adulte fino a 1 m", de: "Metres of trailing stems; juvenile leaves 10 cm, adult up to 1 m",
    tmin: "12 °C", um: "media", err: "Lasciarla in penombra e poi stupirsi che perda la variegatura.", erre: "Leaving it in shade and then wondering why it loses its variegation.",
    gu: "La distanza fra una foglia e l'altra: se si allunga, la luce non basta.", gue: "The spacing between leaves: if it stretches, there isn't enough light." },
  "Spathiphyllum (spatifillo)": { nc: "Giglio della pace", nce: "Peace lily",
    d: "40-60 cm, alcune varietà fino a 1 m", de: "40-60 cm, some varieties to 1 m",
    tmin: "13 °C", um: "medio-alta", err: "Usare il crollo come sveglia: si rialza, ma ogni volta perde qualche radice.", erre: "Using its collapse as a reminder: it recovers, but loses roots each time.",
    gu: "La base del ciuffo: se le foglie esterne ingialliscono a una a una, guarda le radici.", gue: "The base of the clump: if the outer leaves yellow one by one, check the roots." },
  "Maranta leuconeura": { nc: "Pianta della preghiera", nce: "Prayer plant",
    d: "Tappezzante, 25-30 cm di altezza", de: "Ground-hugging, 25-30 cm tall",
    tmin: "15 °C", um: "alta", err: "Acqua del rubinetto: il calcare le secca le punte in poche settimane.", erre: "Tap water: limescale browns the tips within weeks.",
    gu: "Il centro della pianta la sera: se le foglie non si alzano, qualcosa non va.", gue: "The centre of the plant in the evening: if the leaves don't rise, something's wrong." },
  "Calathea": { nc: "Calatea", nce: "Calathea",
    d: "Da 30 cm a 1 m secondo la specie", de: "From 30 cm to 1 m depending on species",
    tmin: "16 °C", um: "alta", err: "Scambiare le punte secche per sete e annaffiare di più.", erre: "Mistaking brown tips for thirst and watering more.",
    gu: "Il bordo delle foglie nuove: è lì che il calcare si vede per primo.", gue: "The edge of the new leaves: that's where limescale shows first." },
  "Fittonia albivenis": { nc: "Pianta mosaico", nce: "Nerve plant",
    d: "Piccolissima: 10-15 cm, si allarga in tappeto", de: "Tiny: 10-15 cm, spreads as a carpet",
    tmin: "15 °C", um: "alta", err: "Lasciarla asciugare del tutto: si affloscia subito e non sempre si riprende.", erre: "Letting it dry out completely: it collapses at once and doesn't always recover.",
    gu: "Le foglie più basse a contatto col terriccio: marciscono per prime.", gue: "The lowest leaves touching the soil: they rot first." },
  "Chlorophytum (spider plant)": { nc: "Nastrino", nce: "Spider plant",
    d: "30-40 cm, più gli stoloni lunghi fino a 1 m", de: "30-40 cm, plus runners up to 1 m",
    tmin: "7 °C", um: "media", err: "Tenerla in bagno al buio pensando che voglia umidità: vuole luce.", erre: "Keeping it in a dark bathroom for the humidity: what it wants is light.",
    gu: "Le punte marroni e la base del ciuffo, dove partono i marciumi da ristagno.", gue: "The brown tips and the base of the clump, where waterlogging rot begins." },
  "Sansevieria (snake plant)": { nc: "Lingua di suocera", nce: "Snake plant",
    d: "Da 20 cm a 1,2 m secondo la varietà", de: "From 20 cm to 1.2 m depending on variety",
    tmin: "10 °C", um: "bassa", err: "Annaffiarla come le altre: è l'unico modo per ucciderla.", erre: "Watering it like the others: that's the only way to kill it.",
    gu: "Il colletto, cioè dove la foglia esce dal terriccio: premi piano, se cede è marciume.", gue: "The collar, where the leaf leaves the soil: press gently — if it gives, it's rot." },
  "Sansevieria intrecciata": { nc: "Lingua di suocera intrecciata", nce: "Braided snake plant",
    d: "40-60 cm, l'intreccio limita la crescita", de: "40-60 cm; the braid limits growth",
    tmin: "10 °C", um: "bassa", err: "Bagnare dall'alto: l'acqua ristagna dove le foglie si incrociano e parte il marciume.", erre: "Watering from above: water pools where the leaves cross and rot starts.",
    gu: "Il punto in cui le foglie si incrociano: lì ristagna l'acqua e comincia il marciume.", gue: "Where the leaves cross: water pools there and rot begins." },
  "Peperomia polybotrya (raindrop)": { nc: "Peperomia goccia", nce: "Raindrop peperomia",
    d: "Compatta: 25-30 cm", de: "Compact: 25-30 cm",
    tmin: "12 °C", um: "media", err: "Rinvasarla in un vaso grande: sta meglio stretta.", erre: "Repotting into a big pot: it prefers to be snug.",
    gu: "I piccioli vicino alla terra: se diventano trasparenti, stai annaffiando troppo.", gue: "The stalks near the soil: if they turn translucent, you're overwatering." },
  "Peperomia obtusifolia": { nc: "Peperomia", nce: "Baby rubber plant",
    d: "25-30 cm, cespugliosa", de: "25-30 cm, bushy",
    tmin: "12 °C", um: "media", err: "Spostarla spesso: gli sbalzi le fanno cadere le foglie.", erre: "Moving it often: sudden changes make it drop leaves.",
    gu: "Le foglie che cadono ancora verdi: è il primo segnale di radici sofferenti.", gue: "Leaves dropping while still green: the first sign of struggling roots." },
  "Phlebodium aureum (felce blu)": { nc: "Felce blu", nce: "Blue star fern",
    d: "Fronde di 40-60 cm, il rizoma striscia in superficie", de: "Fronds 40-60 cm; the rhizome creeps on the surface",
    tmin: "12 °C", um: "alta", err: "Interrare il rizoma: deve restare in superficie o marcisce.", erre: "Burying the rhizome: it must stay on the surface or it rots.",
    gu: "Il rizoma peloso in superficie: deve restare scoperto e sodo, mai interrato né molle.", gue: "The furry rhizome on the surface: it must stay exposed and firm, never buried or soft." },
  "Felce rustica da esterno": { nc: "Felce dei boschi", nce: "Wood fern",
    d: "60-100 cm, muore in superficie d'inverno e ributta", de: "60-100 cm; dies back in winter and returns",
    tmin: "-15 °C", um: "media", err: "Portarla dentro d'inverno: le serve il freddo per riposare.", erre: "Bringing it indoors in winter: it needs the cold to rest.",
    gu: "Il centro del ciuffo a primavera: è da lì che spuntano le fronde nuove arrotolate.", gue: "The centre of the clump in spring: that's where the new curled fronds appear." },
  "Hedera helix (edera)": { nc: "Edera comune", nce: "Common ivy",
    d: "Illimitata: in natura copre facciate intere", de: "Unlimited: in the wild it covers whole walls",
    tmin: "-10 °C", um: "media", err: "Tenerla al caldo secco: è l'invito al ragnetto rosso.", erre: "Keeping it in dry warmth: an open invitation to spider mites.",
    gu: "Il rovescio delle foglie e le ascelle: al caldo secco è il primo posto dove arriva il ragnetto.", gue: "Leaf undersides and axils: in dry warmth that's where mites arrive first." },
  "Pilea peperomioides": { nc: "Pianta delle monete", nce: "Chinese money plant",
    d: "25-30 cm, fa polloni alla base", de: "25-30 cm, produces offsets at the base",
    tmin: "10 °C", um: "media", err: "Non ruotarla: cresce tutta piegata verso la finestra.", erre: "Not turning it: it grows lopsided towards the window.",
    gu: "La base del fusto: se si spoglia e si piega, le manca luce da un lato.", gue: "The base of the stem: if it goes bare and leans, it's short of light on one side." },
  "Hypoestes (polka dot)": { nc: "Pianta pois", nce: "Polka dot plant",
    d: "20-30 cm; va potata o si sfilaccia", de: "20-30 cm; needs pinching or it straggles",
    tmin: "13 °C", um: "medio-alta", err: "Non cimarla: si allunga e si spoglia alla base.", erre: "Not pinching it: it stretches and goes bare at the base.",
    gu: "Le cime: se si allungano e perdono le macchie, serve più luce e una cimatura.", gue: "The tips: if they stretch and lose their spots, it needs more light and a pinch." },
  "Sedum nussbaumerianum": { nc: "Sedum rame", nce: "Coppertone stonecrop",
    d: "Rosette di 6-8 cm su steli che ricadono", de: "Rosettes 6-8 cm on trailing stems",
    tmin: "5 °C", um: "bassa", err: "Lasciarla fuori con la pioggia: l'acqua nel colletto la fa marcire.", erre: "Leaving it out in the rain: water in the crown rots it.",
    gu: "Il centro delle rosette: se ci resta acqua o se le foglie basse si sfaldano, è marciume.", gue: "The centre of the rosettes: water sitting there, or lower leaves turning mushy, means rot." },
  "Philodendron": { nc: "Filodendro", nce: "Philodendron",
    d: "Da 40 cm a diversi metri secondo la specie", de: "From 40 cm to several metres depending on species",
    tmin: "13 °C", um: "media", err: "Tenerlo al sole diretto: le foglie si sbiancano.", erre: "Keeping it in direct sun: the leaves bleach.",
    gu: "Il rovescio delle foglie e il palo: parassiti sotto, radici aeree sopra.", gue: "Leaf undersides and the pole: pests below, aerial roots above." },
};
