/* Plant Care Companion — dati botanici e di cura.
   Autore: Edoardo Giangrandi — © 2026, licenza MIT */

export const PROBLEMI = [
  { id: "marciume-radici", cat: "troppa", s: "Foglie gialle e terriccio ancora bagnato",
    c: "Marciume radicale: le radici affogate non assorbono più, quindi la pianta ingiallisce come se avesse sete. È l'inganno più comune, e chi annaffia di più la finisce.",
    f: ["Sfila il pane di terra e guarda: radici bianche o sode stanno bene, brune e molli sono marce.",
        "Taglia tutto il marcio con forbici pulite, rinvasa in substrato asciutto e più drenante.",
        "Non annaffiare per una settimana e non concimare per un mese."],
    sp: ["Calathea", "Maranta", "Fittonia", "Peperomia", "Phlebodium", "Felce", "Spathiphyllum"] },

  { id: "marciume-colletto", cat: "troppa", s: "Base del fusto molle, scura, che cede al tocco",
    c: "Marciume del colletto: parte dal punto dove il fusto entra nel terriccio, spesso perché l'acqua ristagna lì o è finita nel cuore della rosetta.",
    f: ["Sulle sansevierie e sulle grasse è quasi sempre fatale sotto quel punto: taglia sopra il marcio e fai radicare la parte sana.",
        "Annaffia dal basso o lungo il bordo del vaso, mai al centro."],
    sp: ["Sansevieria", "Sedum", "Crassul"] },

  { id: "substrato-bagnato", cat: "troppa", s: "Il terriccio resta bagnato per più di una settimana",
    c: "Substrato compattato o vaso troppo grande: la terra dove non arrivano radici trattiene acqua e basta.",
    f: ["Rinvasa in un vaso solo 2-4 cm più largo, con più perlite o corteccia.",
        "Verifica che il foro di drenaggio non sia otturato dalle radici."],
    sp: ["Anthurium", "Phlebodium", "Monstera", "Philodendron"] },

  { id: "sete", cat: "poca", s: "Foglie afflosciate di colpo, terriccio asciutto",
    c: "Solo sete. Alcune specie crollano in modo teatrale e si rialzano in un'ora.",
    f: ["Annaffia bene e aspetta: se si rialza era quello.",
        "Se lo fa spesso, accorcia l'intervallo: ogni crollo costa qualche radichetta."],
    sp: ["Spathiphyllum", "Fittonia", "Hypoestes", "Maranta"] },

  { id: "idrorepellente", cat: "poca", s: "L'acqua scorre via subito e il vaso resta leggero",
    c: "Pane di terra asciugato troppo: diventa idrorepellente e l'acqua scivola lungo le pareti senza bagnare niente.",
    f: ["Immergi il vaso in una bacinella per dieci minuti, poi scola bene.",
        "Vale sempre per i substrati a base di corteccia, che sono i più difficili da riumidire."],
    sp: ["Anthurium", "Phlebodium", "Monstera"] },

  { id: "ragnetto", cat: "bestie", s: "Ragnatele finissime tra le foglie, puntini che si muovono",
    c: "Ragnetto rosso. Ama il caldo secco e attacca prima le foglie basse, sul rovescio. È il parassita che uccide più alocasie.",
    f: ["Doccia con acqua tiepida sul rovescio delle foglie, con insistenza.",
        "Avvia un ciclo di neem: tre passate a sette giorni di distanza, la sera.",
        "Alza l'umidità: al secco si riproduce in pochi giorni."],
    sp: ["Alocasia", "Hedera", "Howea", "Monstera", "Anthurium"] },

  { id: "cocciniglia-farinosa", cat: "bestie", s: "Batuffoli bianchi cotonosi dove la foglia incontra il fusto",
    c: "Cocciniglia farinosa. Si nasconde nelle ascelle e sotto i bordi del vaso, e passa da una pianta all'altra se si toccano.",
    f: ["Toglila una a una con un cotton fioc imbevuto di alcol.",
        "Poi neem su tutta la pianta, e isola quella colpita finché non è pulita.",
        "Controlla anche il terriccio: alcune specie stanno sulle radici."],
    sp: ["Anthurium", "Monstera", "Philodendron", "Epipremnum"] },

  { id: "cocciniglia-bruna", cat: "bestie", s: "Scudetti marroni fermi sui piccioli, appiccicaticcio sulle foglie",
    c: "Cocciniglia bruna. Sembrano crosticine e non si muovono: quello che appiccica è la loro melata, su cui poi cresce fumaggine nera.",
    f: ["Staccale con l'unghia o uno spazzolino morbido.",
        "Lava le foglie con acqua e poche gocce di sapone di Marsiglia, poi risciacqua.",
        "Ripeti a distanza di dieci giorni: le uova sotto lo scudetto sopravvivono."],
    sp: ["Hedera", "Howea", "Sansevieria", "Epipremnum"] },

  { id: "sciaridi", cat: "bestie", s: "Moscerini che si alzano dal vaso quando lo muovi",
    c: "Sciaridi. Gli adulti sono innocui, le larve mangiano le radichette e vivono solo in terriccio costantemente umido.",
    f: ["Lascia asciugare i primi 3 cm: senza umido in superficie il ciclo si interrompe.",
        "Uno strato di lapillo o sabbia sopra il terriccio impedisce la deposizione.",
        "Le trappole gialle adesive prendono gli adulti ma non risolvono da sole."],
    sp: ["Felce", "Phlebodium", "Fittonia", "Calathea"] },

  { id: "tripidi", cat: "bestie", s: "Foglie con aree argentate e puntini neri, deformate da nuove",
    c: "Tripidi. Sono minuscoli e velocissimi, e danneggiano le foglie mentre sono ancora arrotolate: il danno si vede quando è già fatto.",
    f: ["Neem ripetuto ogni sette giorni per almeno tre cicli.",
        "Taglia le foglie più colpite: non guariscono.",
        "Sono i più tenaci: aspettati un mese di lavoro."],
    sp: ["Alocasia", "Anthurium", "Monstera"] },

  { id: "macchie-fungine", cat: "funghi", s: "Macchie brune con un alone giallo attorno",
    c: "Macchie fogliari fungine o batteriche. Partono quasi sempre da foglie bagnate che restano umide tutta la notte.",
    f: ["Taglia le foglie colpite e buttale, non nel compost.",
        "Non nebulizzare la sera: le foglie devono asciugare prima del buio.",
        "Aumenta la circolazione d'aria fra le piante."],
    sp: ["Maranta", "Calathea", "Fittonia"] },

  { id: "oidio", cat: "funghi", s: "Patina bianca polverosa sulle foglie",
    c: "Oidio, il mal bianco. Arriva con aria ferma e sbalzi di temperatura, più che con l'umidità.",
    f: ["Pulisci le foglie con un panno umido e isola la pianta.",
        "Bicarbonato in acqua o zolfo bagnabile sulle parti colpite.",
        "Distanzia le piante: l'aria ferma è la causa principale."],
    sp: ["Hypoestes", "Peperomia", "Hedera"] },

  { id: "muffa-terriccio", cat: "funghi", s: "Muffa bianca soffice sulla superficie del terriccio",
    c: "Quasi sempre innocua: sono funghi saprofiti che mangiano materia organica. Segnalano però che quel terriccio resta troppo umido.",
    f: ["Raschia via lo strato superficiale e lascia asciugare di più.",
        "Non serve nessun trattamento: sparisce da sola quando la superficie asciuga."],
    sp: ["Felce", "Phlebodium", "Anthurium"] },

  { id: "sali", cat: "concime", s: "Crosta bianca sul terriccio o sul bordo del vaso",
    c: "Accumulo di sali, da concime in eccesso o acqua dura. I sali richiamano acqua fuori dalle radici e le bruciano.",
    f: ["Dilava: acqua abbondante che esce dal foro, ripetuta tre o quattro volte.",
        "Sospendi il concime per due mesi.",
        "Se l'acqua è dura, passa alla demineralizzata."],
    sp: ["Howea", "Chlorophytum", "Sansevieria", "Dracaena"] },

  { id: "carenza", cat: "concime", s: "Foglie nuove piccole e pallide, crescita ferma in piena stagione",
    c: "Carenza di nutrienti: substrato esaurito o mai concimato. Nei substrati a base di corteccia succede prima, perché trattengono poco.",
    f: ["Riprendi il concime a mezza dose e osserva la foglia successiva.",
        "Se non cambia niente in due mesi, il problema è la luce o le radici, non il cibo."],
    sp: ["Anthurium", "Monstera", "Philodendron"] },

  { id: "punte-secche", cat: "aria", s: "Punte e bordi marroni e croccanti",
    c: "Aria secca, calcare nell'acqua o entrambi. Il sintomo più frainteso di tutti: sembra sete e non lo è.",
    f: ["Passa ad acqua demineralizzata o piovana.",
        "Raggruppa le piante e allontanale dai termosifoni.",
        "Le punte già secche non tornano verdi: taglia seguendo il profilo della foglia."],
    sp: ["Calathea", "Maranta", "Chlorophytum", "Howea", "Fittonia"] },

  { id: "arricciate", cat: "aria", s: "Foglie arricciate verso l'interno",
    c: "La pianta riduce la superficie esposta per perdere meno acqua: aria troppo secca, oppure radici che non riescono ad assorbire.",
    f: ["Controlla prima il terriccio: se è bagnato, il problema sono le radici, non l'aria.",
        "Se è asciutto e l'aria è secca, alza l'umidità raggruppando le piante."],
    sp: ["Fittonia", "Calathea", "Maranta"] },

  { id: "filatura", cat: "luce", s: "Steli lunghi e spogli, foglie piccole e distanti",
    c: "Filatura: la pianta si allunga cercando la luce. È il segnale più affidabile di posizione sbagliata.",
    f: ["Spostala più vicino a una finestra, in modo graduale.",
        "Pota gli steli filati: ricrescerà più compatta.",
        "Sulle variegate la luce scarsa fa anche tornare verdi le parti chiare."],
    sp: ["Monstera", "Hypoestes", "Epipremnum", "Pilea"] },

  { id: "scottatura", cat: "luce", s: "Macchie chiare, sbiancate o secche al centro della foglia",
    c: "Scottatura da sole diretto, spesso attraverso un vetro che concentra il calore.",
    f: ["Sposta la pianta o schermala con una tenda leggera.",
        "Le parti bruciate non guariscono: si taglia la foglia solo se è compromessa per più di metà."],
    sp: ["Maranta", "Calathea", "Phlebodium", "Fittonia"] },
];

export const EN_PROBLEMI = {
  "marciume-radici": { s: "Yellow leaves and soil still wet",
    c: "Root rot: drowned roots stop absorbing, so the plant yellows as if it were thirsty. It's the commonest trap, and watering more finishes it off.",
    f: ["Slide the root ball out and look: white firm roots are fine, brown mushy ones are rotten.",
        "Cut away everything rotten with clean scissors, repot into dry, sharper-draining mix.",
        "Don't water for a week and don't feed for a month."] },
  "marciume-colletto": { s: "Base of the stem soft, dark, giving way",
    c: "Crown rot: it starts where the stem meets the soil, usually because water sits there or has run into the centre of the rosette.",
    f: ["On snake plants and succulents it's almost always fatal below that point: cut above the rot and root the healthy part.",
        "Water from below or along the rim of the pot, never into the middle."] },
  "substrato-bagnato": { s: "The soil stays wet for more than a week",
    c: "Compacted mix or an oversized pot: soil with no roots in it just holds water.",
    f: ["Repot into a pot only 2-4 cm wider, with more perlite or bark.",
        "Check the drainage hole isn't blocked by roots."] },
  "sete": { s: "Leaves suddenly collapsed, soil dry",
    c: "Just thirst. Some species faint dramatically and stand back up within the hour.",
    f: ["Water well and wait: if it recovers, that was it.",
        "If it happens often, shorten the interval: every collapse costs a few root hairs."] },
  "idrorepellente": { s: "Water runs straight through and the pot stays light",
    c: "The root ball dried out too far: it turns water-repellent and the water slides down the sides without wetting anything.",
    f: ["Stand the pot in a basin for ten minutes, then drain well.",
        "Always true for bark-based mixes, the hardest of all to re-wet."] },
  "ragnetto": { s: "Very fine webbing between leaves, moving dots",
    c: "Spider mites. They love dry warmth and start on the lower leaves, underneath. The pest that kills the most alocasias.",
    f: ["Shower with lukewarm water on the undersides, thoroughly.",
        "Start a neem cycle: three passes seven days apart, in the evening.",
        "Raise the humidity: in dry air they breed within days."] },
  "cocciniglia-farinosa": { s: "White cottony tufts where leaf meets stem",
    c: "Mealybugs. They hide in leaf axils and under the pot rim, and move between plants that touch.",
    f: ["Remove them one by one with a cotton bud dipped in alcohol.",
        "Then neem over the whole plant, and isolate it until it's clean.",
        "Check the soil too: some species live on the roots."] },
  "cocciniglia-bruna": { s: "Brown scales stuck on the stalks, sticky leaves",
    c: "Brown scale. They look like little scabs and don't move: the stickiness is their honeydew, on which black sooty mould then grows.",
    f: ["Scrape them off with a fingernail or a soft toothbrush.",
        "Wash the leaves with water and a few drops of mild soap, then rinse.",
        "Repeat after ten days: the eggs under the scale survive."] },
  "sciaridi": { s: "Small flies rising from the pot when you move it",
    c: "Fungus gnats. The adults are harmless, the larvae eat root hairs and only live in constantly damp compost.",
    f: ["Let the top 3 cm dry out: without surface moisture the cycle breaks.",
        "A layer of grit or sand on top stops them laying.",
        "Yellow sticky traps catch adults but don't solve it alone."] },
  "tripidi": { s: "Silvery patches with black dots, new leaves deformed",
    c: "Thrips. Tiny and fast, they damage leaves while still furled: you see the damage once it's done.",
    f: ["Neem repeated every seven days for at least three cycles.",
        "Cut the worst leaves: they don't heal.",
        "The most stubborn of all: expect a month of work."] },
  "macchie-fungine": { s: "Brown spots with a yellow halo",
    c: "Fungal or bacterial leaf spot. Almost always starts from wet leaves left damp overnight.",
    f: ["Cut off affected leaves and bin them, not the compost.",
        "Don't mist in the evening: leaves must dry before dark.",
        "Improve airflow between plants."] },
  "oidio": { s: "White powdery film on the leaves",
    c: "Powdery mildew. It comes with still air and temperature swings, more than with humidity.",
    f: ["Wipe the leaves with a damp cloth and isolate the plant.",
        "Bicarbonate in water, or wettable sulphur, on affected parts.",
        "Space the plants out: still air is the main cause."] },
  "muffa-terriccio": { s: "Soft white mould on the surface of the soil",
    c: "Almost always harmless: saprophytic fungi eating organic matter. It does tell you that mix stays too wet.",
    f: ["Scrape off the top layer and let it dry more.",
        "No treatment needed: it goes when the surface dries."] },
  "sali": { s: "White crust on the soil or the pot rim",
    c: "Salt build-up, from over-feeding or hard water. Salts pull water back out of the roots and burn them.",
    f: ["Flush it: plenty of water running out of the hole, three or four times over.",
        "Stop feeding for two months.",
        "If your water is hard, switch to distilled."] },
  "carenza": { s: "New leaves small and pale, growth stalled in season",
    c: "Nutrient shortage: exhausted mix, or never fed. It happens sooner in bark-based mixes, which hold little.",
    f: ["Resume feeding at half strength and watch the next leaf.",
        "If nothing changes in two months, the problem is light or roots, not food."] },
  "punte-secche": { s: "Brown, crispy tips and edges",
    c: "Dry air, limescale in the water, or both. The most misread symptom there is: it looks like thirst and isn't.",
    f: ["Switch to distilled or rainwater.",
        "Group the plants together and move them away from radiators.",
        "Tips already brown won't turn green again: trim following the leaf outline."] },
  "arricciate": { s: "Leaves curling inwards",
    c: "The plant is reducing its exposed surface to lose less water: air too dry, or roots unable to absorb.",
    f: ["Check the soil first: if it's wet, the problem is the roots, not the air.",
        "If it's dry and the air is dry, raise humidity by grouping plants."] },
  "filatura": { s: "Long bare stems, small widely spaced leaves",
    c: "Etiolation: the plant is stretching towards light. The most reliable sign of a wrong spot.",
    f: ["Move it closer to a window, gradually.",
        "Prune the stretched stems: it will regrow more compact.",
        "On variegated plants, low light also turns the pale parts green again."] },
  "scottatura": { s: "Pale, bleached or dry patches in the middle of the leaf",
    c: "Sunburn from direct sun, often through glass that concentrates the heat.",
    f: ["Move the plant or screen it with a light curtain.",
        "Burnt areas don't heal: only remove the leaf if more than half is gone."] },
};
