/* Plant Care Companion — dati botanici e di cura.
   Autore: Edoardo Giangrandi — © 2026, licenza MIT */

export const SPECIE = [
  { nome: "Monstera deliciosa", giorni: 8, luce: "Luce indiretta brillante", ill: "deliciosa" },
  { nome: "Monstera adansonii", giorni: 7, luce: "Luce indiretta brillante", ill: "adansonii" },
  { nome: "Monstera adansonii Mint (variegata)", giorni: 9, luce: "Luce indiretta brillante", ill: "adansonii-solo" },
  { nome: "Howea forsteriana (kentia)", giorni: 9, luce: "Luce indiretta", ill: "palma" },
  { nome: "Epipremnum aureum (pothos)", giorni: 8, luce: "Tollera la penombra", ill: "pothos" },
  { nome: "Alocasia", giorni: 7, luce: "Luce indiretta brillante", ill: "alocasia" },
  { nome: "Alocasia amazonica (Polly)", giorni: 6, luce: "Luce indiretta brillante", ill: "polly" },
  { nome: "Anthurium regale", giorni: 6, luce: "Luce indiretta brillante", ill: "anthurium-regale" },
  { nome: "Anthurium warocqueanum", giorni: 5, luce: "Luce indiretta brillante", ill: "anthurium-serra" },
  { nome: "Hypoestes (polka dot)", giorni: 3, luce: "Luce indiretta brillante", ill: "polkadot" },
  { nome: "Peperomia polybotrya (raindrop)", giorni: 13, luce: "Luce indiretta brillante", ill: "raindrop" },
  { nome: "Peperomia obtusifolia", giorni: 12, luce: "Luce indiretta", ill: "peperomia" },
  { nome: "Maranta leuconeura", giorni: 4, luce: "Luce indiretta", ill: "maranta" },
  { nome: "Calathea", giorni: 5, luce: "Luce indiretta", ill: "calathea" },
  { nome: "Fittonia albivenis", giorni: 3, luce: "Luce indiretta", ill: "fittonia" },
  { nome: "Chlorophytum (spider plant)", giorni: 6, luce: "Luce indiretta brillante", ill: "spider" },
  { nome: "Sansevieria (snake plant)", giorni: 21, luce: "Qualsiasi luce", ill: "snake" },
  { nome: "Sansevieria intrecciata", giorni: 21, luce: "Qualsiasi luce", ill: "snake-intrecciata" },
  { nome: "Felce", giorni: 4, luce: "Luce indiretta", ill: "felce" },
  { nome: "Phlebodium aureum (felce blu)", giorni: 6, luce: "Luce indiretta brillante", ill: "felce-blu" },
  { nome: "Felce rustica da esterno", giorni: 4, luce: "Luce indiretta", ill: "felce-montagna" },
  { nome: "Sedum nussbaumerianum", giorni: 18, luce: "Sole diretto", ill: "sedum" },
  { nome: "Hedera helix (edera)", giorni: 6, luce: "Luce indiretta", ill: "edera-acqua" },
  { nome: "Pilea peperomioides", giorni: 8, luce: "Luce indiretta brillante", ill: "pilea-acqua" },
  { nome: "Philodendron", giorni: 8, luce: "Tollera la penombra", ill: "pothos" },
  { nome: "Spathiphyllum (spatifillo)", giorni: 5, luce: "Luce indiretta", ill: "spatifillo" },
  { nome: "Altro", giorni: 7, luce: "", ill: "generica" },
];

export const PROFILI = {
  "Monstera deliciosa": { giorni: 8, concime: 21, miscela: "aroidee-terrestri", rinvaso: 24, sostegno: "palo-cocco",
    spray: true, pulizia: true, rotazione: true, tipoAcqua: "rubinetto",
    metodo: "A pioggia lenta finché esce dal foro, poi svuota il sottovaso.",
    consiglio: "Luce indiretta forte: vicino a una finestra, mai sul davanzale al sole." },
  "Monstera adansonii": { giorni: 7, concime: 21, miscela: "aroidee-terrestri", rinvaso: 18, sostegno: "palo-cocco",
    spray: true, pulizia: true, rotazione: true, tipoAcqua: "rubinetto",
    metodo: "Bagna anche il palo di cocco, non solo il terriccio.",
    consiglio: "Luce indiretta forte, mai sole diretto." },
  "Monstera adansonii Mint (variegata)": { giorni: 9, concime: 24, miscela: "aroidee-terrestri", rinvaso: 18, sostegno: "palo-cocco",
    spray: true, pulizia: true, rotazione: true, tipoAcqua: "rubinetto",
    metodo: "Bagna anche il palo. La variegatura mint fa fotosintesi, quindi beve più di una variegata bianca.",
    consiglio: "Luce indiretta forte: i settori chiari lavorano, ma il sole pieno li brucerebbe." },
  "Alocasia": { giorni: 7, concime: 21, miscela: "aroidee-terrestri", rinvaso: 12, rotazione: true, spray: true, pulizia: true,
    tipoAcqua: "rubinetto", metodo: "Abbondante fino al drenaggio, poi lascia asciugare i primi 3 cm.",
    consiglio: "Luce forte e aria umida. Controlla il rovescio delle foglie: il ragnetto rosso è il suo nemico." },
  "Alocasia amazonica (Polly)": { giorni: 6, concime: 21, miscela: "aroidee-terrestri", rinvaso: 12, rotazione: true, spray: true, pulizia: true,
    tipoAcqua: "rubinetto", metodo: "Abbondante fino al drenaggio, poi svuota il sottovaso: non deve restare a mollo.",
    consiglio: "Luce indiretta forte e umidità alta, lontano da spifferi e termosifoni." },
  "Anthurium regale": { giorni: 6, concime: 14, miscela: "aroidee-epifite", rinvaso: 12, radicante: true, rotazione: true,
    tipoAcqua: "demineralizzata", metodo: "Immersione: la corteccia respinge l'acqua versata dall'alto. Mai sulle foglie.",
    consiglio: "Vuole il 70% di umidità: il bagno è l'unica stanza normale che ci arriva." },
  "Anthurium warocqueanum": { giorni: 5, concime: 14, miscela: "aroidee-epifite", rinvaso: 12, radicante: true,
    tipoAcqua: "demineralizzata", metodo: "Nebulizza lo sfagno finché è umido, mai fradicio.",
    consiglio: "Umidità altissima: da piccola vive meglio in una serretta." },
  "Howea forsteriana (kentia)": { giorni: 9, concime: 30, miscela: "palme", rinvaso: 36, rotazione: true, spray: true, pulizia: true,
    tipoAcqua: "riposata una notte", metodo: "Abbondante fino al drenaggio, poi lascia asciugare i primi 3-4 cm.",
    consiglio: "Tollera la luce scarsa meglio di quasi tutte, purché senza sole diretto." },
  "Epipremnum aureum (pothos)": { giorni: 8, concime: 21, miscela: "facili", rinvaso: 18, sostegno: "palo-cocco",
    spray: true, pulizia: true, rotazione: true, tipoAcqua: "rubinetto",
    metodo: "A pioggia fino al drenaggio, poi svuota il sottovaso.",
    consiglio: "In luce forte tiene la variegatura, in penombra torna verde." },
  "Spathiphyllum (spatifillo)": { giorni: 5, concime: 21, miscela: "aroidee-terrestri", rinvaso: 18, rotazione: true, spray: true, pulizia: true,
    tipoAcqua: "riposata una notte", metodo: "Abbondante fino al drenaggio. Non aspettare che si affloscia.",
    consiglio: "Sopravvive in penombra, ma per fiorire servono due ore di luce indiretta forte." },
  "Maranta leuconeura": { giorni: 4, concime: 21, miscela: "marantacee", rinvaso: 18, rotazione: true, spray: true,
    tipoAcqua: "demineralizzata", metodo: "Immersione dal basso, terriccio sempre appena umido.",
    consiglio: "Umidità alta e luce indiretta: il bagno è il posto naturale." },
  "Calathea": { giorni: 5, concime: 21, miscela: "marantacee", rinvaso: 18, rotazione: true, spray: true,
    tipoAcqua: "demineralizzata", metodo: "Immersione dal basso. Le punte secche vengono dal calcare, non dalla sete.",
    consiglio: "Umidità alta, luce indiretta bassa, acqua senza calcare." },
  "Fittonia albivenis": { giorni: 3, concime: 21, miscela: "felci", rinvaso: 15, rotazione: true, spray: true,
    tipoAcqua: "demineralizzata", metodo: "Dal basso e poca alla volta: il terriccio deve restare appena umido, sempre.",
    consiglio: "Umidità alta e luce indiretta bassa: sta bene accanto alle marantacee." },
  "Chlorophytum (spider plant)": { giorni: 6, concime: 30, miscela: "facili", rinvaso: 12, rotazione: true, spray: true, pulizia: true,
    tipoAcqua: "demineralizzata", metodo: "Abbondante fino al drenaggio, poi scola tutto.",
    consiglio: "Vuole luce brillante, non umidità: non è una pianta da bagno buio." },
  "Sansevieria (snake plant)": { giorni: 21, concime: 60, miscela: "sansevierie", rinvaso: 36,
    tipoAcqua: "rubinetto", metodo: "Abbondante ma rarissimo, e mai nel cuore della rosetta.",
    consiglio: "Indifferente alla luce scarsa. L'unico modo per ucciderla è annaffiarla troppo." },
  "Sansevieria intrecciata": { giorni: 21, concime: 60, miscela: "sansevierie", rinvaso: 36,
    tipoAcqua: "rubinetto", metodo: "Dal basso, così non ristagna dove le foglie si incrociano.",
    consiglio: "Come la sansevieria normale, ma guarda il punto d'incrocio: è lì che marcisce." },
  "Peperomia polybotrya (raindrop)": { giorni: 13, concime: 45, miscela: "peperomie", rinvaso: 30, rotazione: true,
    tipoAcqua: "rubinetto", metodo: "Immersione dal basso, poi scola bene. Foglie asciutte.",
    consiglio: "Luce indiretta. Stretta nel vaso va benissimo." },
  "Peperomia obtusifolia": { giorni: 12, concime: 45, miscela: "peperomie", rinvaso: 30, rotazione: true,
    tipoAcqua: "rubinetto", metodo: "Poca ma regolare, dal basso. Gli sbalzi le fanno cadere le foglie.",
    consiglio: "Luce indiretta, lontano da correnti e sbalzi di temperatura." },
  "Phlebodium aureum (felce blu)": { giorni: 6, concime: 30, miscela: "felci-epifite", rinvaso: 24, rotazione: true, spray: true,
    tipoAcqua: "demineralizzata", metodo: "Bagna il substrato senza mai coprire il rizoma in superficie.",
    consiglio: "Epifita: il rizoma peloso deve restare in superficie, mai interrato." },
  "Felce": { giorni: 4, concime: 30, miscela: "felci", rinvaso: 18, rotazione: true, spray: true,
    tipoAcqua: "demineralizzata", metodo: "Poca alla volta, ma il terriccio non deve mai asciugare del tutto.",
    consiglio: "Vuole aria umida più che terra bagnata." },
  "Felce rustica da esterno": { giorni: 4, concime: 30, miscela: "felci", rinvaso: 24,
    tipoAcqua: "piovana", metodo: "Solo se il terriccio è asciutto in profondità: fuori ci pensa spesso la pioggia.",
    consiglio: "Mezz'ombra all'aperto, riparata dal sole delle ore centrali e dal vento." },
  "Hedera helix (edera)": { giorni: 6, concime: 30, miscela: "facili", rinvaso: 18, sostegno: "traliccio", spray: true,
    tipoAcqua: "riposata una notte", metodo: "Regolare, senza mai lasciare il vaso a mollo.",
    consiglio: "Fresco e luminoso. Si aggrappa solo a superfici ruvide: legno, corda, cocco." },
  "Pilea peperomioides": { giorni: 8, concime: 28, miscela: "facili", rinvaso: 18, rotazione: true,
    tipoAcqua: "rubinetto", metodo: "Abbondante fino al drenaggio, poi lascia asciugare i primi centimetri.",
    consiglio: "Luce indiretta brillante, e ruotala ogni settimana o cresce storta." },
  "Hypoestes (polka dot)": { giorni: 3, concime: 21, miscela: "facili", rinvaso: 12, rotazione: true,
    tipoAcqua: "rubinetto", metodo: "Acqua nel sottovaso, mai sulle foglie.",
    consiglio: "Luce brillante o perde le macchie rosa e si allunga." },
  "Sedum nussbaumerianum": { giorni: 18, concime: 60, miscela: "grasse", rinvaso: 36, rotazione: true,
    tipoAcqua: "rubinetto", metodo: "Abbondante ma rarissima, mai sulle rosette: l'acqua nel colletto le fa marcire.",
    consiglio: "Più sole prende, più le foglie virano al rame. In ombra restano verdi e si allungano." },
  "Philodendron": { giorni: 8, concime: 21, miscela: "aroidee-terrestri", rinvaso: 18, sostegno: "palo-cocco",
    spray: true, pulizia: true, rotazione: true, tipoAcqua: "rubinetto",
    metodo: "A pioggia fino al drenaggio, poi svuota il sottovaso.",
    consiglio: "Luce indiretta, tollera la penombra." },
  "Altro": { giorni: 7, concime: 28, miscela: "facili", rinvaso: 18, rotazione: true, tipoAcqua: "rubinetto",
    metodo: "", consiglio: "" },
};

export const EN_PROFILI = {
  "Monstera deliciosa": { metodo: "Slow soak until it runs from the hole, then empty the saucer.",
    consiglio: "Bright indirect light: near a window, never on a sunny sill." },
  "Monstera adansonii": { metodo: "Wet the coir pole too, not just the compost.",
    consiglio: "Bright indirect light, never direct sun." },
  "Monstera adansonii Mint (variegata)": { metodo: "Wet the pole too. Mint variegation photosynthesises, so it drinks more than a white variegate.",
    consiglio: "Bright indirect light: the pale sectors work, but full sun would scorch them." },
  "Alocasia": { metodo: "Soak until it drains, then let the top 3 cm dry.",
    consiglio: "Strong light and humid air. Check the leaf undersides: spider mites are its enemy." },
  "Alocasia amazonica (Polly)": { metodo: "Soak until it drains, then empty the saucer: it must not sit in water.",
    consiglio: "Bright indirect light and high humidity, away from draughts and radiators." },
  "Anthurium regale": { metodo: "Soak the pot: bark repels water poured from above. Never on the leaves.",
    consiglio: "It wants 70% humidity: a bathroom is the only ordinary room that gets there." },
  "Anthurium warocqueanum": { metodo: "Mist the sphagnum until damp, never soaking.",
    consiglio: "Very high humidity: when small it does better in a propagator." },
  "Howea forsteriana (kentia)": { metodo: "Soak until it drains, then let the top 3-4 cm dry.",
    consiglio: "Takes low light better than almost any other, as long as there's no direct sun." },
  "Epipremnum aureum (pothos)": { metodo: "Water until it drains, then empty the saucer.",
    consiglio: "In strong light it keeps its variegation; in shade it turns green again." },
  "Spathiphyllum (spatifillo)": { metodo: "Soak until it drains. Don't wait for it to flop.",
    consiglio: "It survives in shade, but needs two hours of bright indirect light to flower." },
  "Maranta leuconeura": { metodo: "Bottom watering, compost always just damp.",
    consiglio: "High humidity and indirect light: a bathroom is its natural home." },
  "Calathea": { metodo: "Bottom watering. Brown tips come from limescale, not thirst.",
    consiglio: "High humidity, low indirect light, water without limescale." },
  "Fittonia albivenis": { metodo: "From below and little at a time: the compost must stay just damp, always.",
    consiglio: "High humidity and low indirect light: happy next to prayer plants." },
  "Chlorophytum (spider plant)": { metodo: "Soak until it drains, then let it drain fully.",
    consiglio: "It wants bright light, not humidity: it isn't a plant for a dark bathroom." },
  "Sansevieria (snake plant)": { metodo: "Plenty but very rarely, and never into the heart of the rosette.",
    consiglio: "Indifferent to low light. The only way to kill it is to overwater." },
  "Sansevieria intrecciata": { metodo: "From below, so water doesn't pool where the leaves cross.",
    consiglio: "Like a normal snake plant, but watch the crossing point: that's where rot starts." },
  "Peperomia polybotrya (raindrop)": { metodo: "Bottom watering, then drain well. Keep the leaves dry.",
    consiglio: "Indirect light. Being pot-bound suits it fine." },
  "Peperomia obtusifolia": { metodo: "Little but regularly, from below. Swings make it drop leaves.",
    consiglio: "Indirect light, away from draughts and temperature swings." },
  "Phlebodium aureum (felce blu)": { metodo: "Water the mix without ever covering the rhizome on the surface.",
    consiglio: "Epiphyte: the furry rhizome must stay on the surface, never buried." },
  "Felce": { metodo: "Little at a time, but the compost must never dry out completely.",
    consiglio: "It wants humid air more than wet soil." },
  "Felce rustica da esterno": { metodo: "Only if the compost is dry deep down: outdoors the rain often does it for you.",
    consiglio: "Partial shade outdoors, sheltered from midday sun and strong wind." },
  "Hedera helix (edera)": { metodo: "Regular, never leaving the pot standing in water.",
    consiglio: "Cool and bright. It only grips rough surfaces: wood, rope, coir." },
  "Pilea peperomioides": { metodo: "Soak until it drains, then let the top few centimetres dry.",
    consiglio: "Bright indirect light, and turn it weekly or it grows lopsided." },
  "Hypoestes (polka dot)": { metodo: "Water into the saucer, never onto the leaves.",
    consiglio: "Bright light or it loses the pink and stretches." },
  "Sedum nussbaumerianum": { metodo: "Plenty but very rarely, never onto the rosettes: water in the crown rots them.",
    consiglio: "The more sun it gets, the more the leaves turn copper. In shade they stay green and stretch." },
  "Philodendron": { metodo: "Water until it drains, then empty the saucer.",
    consiglio: "Indirect light, tolerates shade." },
  "Altro": { metodo: "", consiglio: "" },
};

export const VASI = {
  plastica:   { t: "Plastica", te: "Plastic", f: 1,
    n: "", ne: "" },
  terracotta: { t: "Terracotta", te: "Terracotta", f: 0.7,
    n: "La terracotta traspira dai lati: asciuga in circa un terzo di tempo in meno rispetto alla plastica.",
    ne: "Terracotta breathes through its walls: it dries roughly a third faster than plastic." },
  ceramica:   { t: "Ceramica smaltata", te: "Glazed ceramic", f: 1.05,
    n: "Lo smalto chiude i pori: si comporta come la plastica, ma spesso è più pesante e trattiene di più sul fondo.",
    ne: "The glaze seals the pores: it behaves like plastic, but often holds more water at the bottom." },
  cemento:    { t: "Cemento", te: "Concrete", f: 0.85,
    n: "Poroso ma spesso: asciuga più in fretta della plastica, meno della terracotta.",
    ne: "Porous but thick: dries faster than plastic, slower than terracotta." },
  tessuto:    { t: "Tessuto o geotessile", te: "Fabric pot", f: 0.6,
    n: "Traspira da tutta la superficie: asciuga prima di ogni altro vaso, e le radici si fermano al bordo invece di girare.",
    ne: "It breathes across the whole surface: dries faster than any other pot, and roots stop at the edge instead of circling." },
  vetro:      { t: "Vetro", te: "Glass", f: 1.15,
    n: "Non traspira per niente, e la luce sulle radici favorisce le alghe. Tienilo lontano dal sole diretto.",
    ne: "No transpiration at all, and light on the roots encourages algae. Keep it out of direct sun." },
};

export const CANDIDATE = [
  { f: "Araceae", n: "Scindapsus pictus", nc: "Scindapsus argentato", nce: "Satin pothos",
    p: "Rampicante come i tuoi pothos, ma con foglie argentate e ancora più tollerante alla penombra.",
    pe: "A climber like your pothos, with silvered leaves and even more tolerant of shade.",
    t: "13 °C", u: "media", w: "Scindapsus_pictus" },
  { f: "Araceae", n: "Zamioculcas zamiifolia", nc: "Zamioculcas", nce: "ZZ plant",
    p: "La più indistruttibile delle Araceae: rizoma che immagazzina acqua, sopporta mesi di dimenticanza.",
    pe: "The toughest of the Araceae: a water-storing rhizome, it takes months of neglect.",
    t: "12 °C", u: "bassa", w: "Zamioculcas" },
  { f: "Araceae", n: "Syngonium podophyllum", nc: "Singonio", nce: "Arrowhead vine",
    p: "Cresce in fretta e cambia forma delle foglie con l'età: parte a punta di freccia e finisce lobata.",
    pe: "Fast growing, and its leaves change shape with age: from arrowhead to lobed.",
    t: "15 °C", u: "medio-alta", w: "Syngonium_podophyllum" },
  { f: "Marantaceae", n: "Ctenanthe burle-marxii", nc: "Ctenante", nce: "Fishbone prayer plant",
    p: "Stesse esigenze delle tue marantacee, ma più robusta e con un disegno a lisca di pesce.",
    pe: "Same needs as your prayer plants, but sturdier, with a fishbone pattern.",
    t: "15 °C", u: "alta", w: "Ctenanthe" },
  { f: "Marantaceae", n: "Stromanthe sanguinea", nc: "Stromante", nce: "Stromanthe",
    p: "Rovescio delle foglie rosso acceso: nelle stesse condizioni della Religiosa.",
    pe: "Vivid red leaf undersides; same conditions as your prayer plant.",
    t: "16 °C", u: "alta", w: "Stromanthe" },
  { f: "Piperaceae", n: "Peperomia argyreia", nc: "Peperomia cocomero", nce: "Watermelon peperomia",
    p: "Foglie a righe come un cocomero, stesse cure delle peperomie che hai già.",
    pe: "Leaves striped like a watermelon, same care as the peperomias you already keep.",
    t: "13 °C", u: "media", w: "Peperomia_argyreia" },
  { f: "Asparagaceae", n: "Aspidistra elatior", nc: "Aspidistra", nce: "Cast iron plant",
    p: "La chiamano pianta di ghisa: regge penombra, freddo e trascuratezza meglio di tutte.",
    pe: "They call it the cast iron plant: it takes shade, cold and neglect better than anything.",
    t: "5 °C", u: "bassa", w: "Aspidistra_elatior" },
  { f: "Crassulaceae", n: "Crassula ovata", nc: "Albero di giada", nce: "Jade plant",
    p: "Stesse cure delle Sorelle, ma diventa un alberello e vive decenni.",
    pe: "Same care as your sedum, but it becomes a small tree and lives for decades.",
    t: "7 °C", u: "bassa", w: "Crassula_ovata" },
  { f: "Polypodiaceae", n: "Platycerium bifurcatum", nc: "Felce a corna d'alce", nce: "Staghorn fern",
    p: "Epifita come il Phlebodium: si coltiva su tavoletta invece che in vaso.",
    pe: "An epiphyte like your blue fern: grown on a board instead of in a pot.",
    t: "10 °C", u: "alta", w: "Platycerium_bifurcatum" },
  { f: "Arecaceae", n: "Chamaedorea elegans", nc: "Palma da salotto", nce: "Parlour palm",
    p: "Piccola e paziente come la kentia, ma sta in mezzo metro.",
    pe: "Small and patient like your kentia, but it stays under half a metre.",
    t: "12 °C", u: "media", w: "Chamaedorea_elegans" },
  { f: "Acanthaceae", n: "Aphelandra squarrosa", nc: "Pianta zebra", nce: "Zebra plant",
    p: "Nervature bianche marcate, stesse condizioni della fittonia ma con più luce.",
    pe: "Bold white veins; like your fittonia but wanting more light.",
    t: "16 °C", u: "alta", w: "Aphelandra_squarrosa" },
];
